name: Deploy on Enviroment Dev
env:
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  JWT_ACCESS_SECRETKEY: "ie104_access_token"
  JWT_ACCESS_EXPIRY: "1d"
  JWT_REFRESH_SECRETKEY: "ie104_refresh_token"
  JWT_REFRESH_EXPIRY: "3d"
  JWT_SIGNUP_TOKEN: "signup"
  JWT_SIGNUP_EXPIRY: "1d"
  URL_CLIENT: "http://fe.ie104.customafk.com/signup/token"
  RESEND_KEY: ${{secrets.RESEND_KEY}}
  AWS_ACCESSKEY_ID: ${{secrets.AWS_ACCESSKEY_ID}}
  AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
  AWS_BUCKET_NAME: ${{secrets.AWS_BUCKET_NAME}}
  CLIENT_ID: ${{secrets.CLIENT_ID}}
  API_KEY: ${{secrets.API_KEY}}
on:
  pull_request:
    branches:
      - "master"
      - "developement"
    types:
      - closed
jobs:
  test_preview:
    strategy:
      matrix:
        bun-verison: [1.x.x]
    runs-on: self-hosted
    steps:
      - name: Check code
        uses: actions/checkout@v4

      - name: Install package use yarn
        run: |
          echo "We using bun to install package!"
          bun install

      - name: Check format
        run: |
          echo "Using pettier check"
          bun format

      - name: Edit .env
        run: |

          pm2 stop "ie104-back-end"
          rm -rf .env
          touch .env

          echo "#DATABASE" >> .env
          echo "DATABASE_URL=${{env.DATABASE_URL}}" >> .env
          echo "#SERVER RUNNING" >> .env
          echo "SERVER_PORT=3000" >> .env

          echo "#Enviroment in Server"
          echo "JWT_ACCESS_SECRETKEY=${{env.JWT_ACCESS_SECRETKEY}}" >> .env
          echo "JWT_ACCESS_EXPIRY=${{env.JWT_ACCESS_EXPIRY}}" >> .env
          echo "JWT_REFRESH_SECRETKEY=${{env.JWT_REFRESH_SECRETKEY}}" >> .env
          echo "JWT_REFRESH_EXPIRY=${{env.JWT_REFRESH_EXPIRY}}" >> .env
          echo "JWT_SIGNUP_TOKEN=${{env.JWT_SIGNUP_TOKEN}}" >> .env
          echo "JWT_SIGNUP_EXPIRY=${{env.JWT_SIGNUP_EXPIRY}}" >> .env

          echo "#SEND EMAIL CHECK"
          echo "URL_CLIENT=${{env.URL_CLIENT}}" >> .env
          echo "RESEND_KEY=${{env.RESEND_KEY}}" >> .env

          echo "#AWS key"
          echo "AWS_REGION=ap-southeast-1" >> .env
          echo "AWS_ACCESSKEY_ID=${{env.AWS_ACCESSKEY_ID}}" >> .env
          echo "AWS_SECRET_ACCESS_KEY=${{env.AWS_SECRET_ACCESS_KEY}}" >> .env
          echo "AWS_BUCKET_NAME=${{env.AWS_BUCKET_NAME}}" >> .env
          echo "#KEY QR PAY"
          echo "CLIENT_ID=${{env.CLIENT_ID}}" >> .env
          echo "API_KEY=${{env.API_KEY}}" >> .env
      - name: Build bunx
        run: |
          echo "Bun is Building"
          bun db:pull
          bun db:generate
          bun build:server
          pm2 restart "ie104-back-end"
