name: Deploy on Enviroment Dev
env:
  DATABASE_URL: ${{secrets.DATABASE_URL}}
  JWT_ACCESS_SECRETKEY: "ie104_access_token"
  JWT_ACCESS_EXPIRY: "1d"
  JWT_REFRESH_SECRETKEY: "ie104_refresh_token"
  JWT_REFRESH_EXPIRY: "3d"
  AWS_ACCESSKEY_ID: ${{secrets.AWS_ACCESSKEY_ID}}
  AWS_SERCET_ACCESS_KEY: ${{secrets.AWS_SERCET_ACCESS_KEY}}
  AWS_BUCKET_NAME: ${{secrets.AWS_BUCKET_NAME}}
  CLIENT_ID: ${{secrets.CLIENT_ID}}
  API_KEY: ${{secrets.API_KEY}}
on:
  pull_request:
    branches:
      - "master"
      - "developement"
    types:
      - closed
jobs:
  test_preview:
    strategy:
      matrix:
        bun-verison: [1.x.x]
    runs-on: ubuntu-latest
    steps:
      - name: Check code
        uses: actions/checkout@v4

      - name: Setup Bunx
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install package use yarn
        run: |
          echo "We using bun to install package!"
          bun install

      - name: Check format
        run: |
          echo "Using pettier check"
          bun format

      - name: Edit .env
        run: |
          echo "DATABASE_URL=${{env.DATABASE_URL}}" >> .env
          echo "SERVER_PORT=3000" >> .env
          echo "JWT_ACCESS_SECRETKEY=${{env.JWT_ACCESS_SECRETKEY}}" >> .env
          echo "JWT_ACCESS_EXPIRY=${{env.JWT_ACCESS_EXPIRY}}" >> .env
          echo "JWT_REFRESH_SECRETKEY=${{env.JWT_REFRESH_SECRETKEY}}" >> .env
          echo "JWT_REFRESH_EXPIRY=${{env.JWT_REFRESH_EXPIRY}}" >> .env
          echo "AWS_REGION=ap-southeast-1" >> .env
          echo "AWS_ACCESSKEY_ID=${{env.AWS_ACCESSKEY_ID}}" >> .env
          echo "AWS_SERCET_ACCESS_KEY=${{env.AWS_SERCET_ACCESS_KEY}}" >> .env
          echo "AWS_BUCKET_NAME=${{env.AWS_BUCKET_NAME}}" >> .env
          echo "CLIENT_ID=${{env.client_id}}" >> .env
          echo "API_KEY=${{env.API_KEY}}" >> .env
      - name: Build bunx
        run: |
          echo "Bun is Building"
          bunx prisma generate deploy
          bun build:server
      - name: Run server
        run: |
          ./build/server
